import type React from 'react';

export const listeningMakerTokens = {
  ink: '#111827',
  body: '#374151',
  muted: '#6b7280',
  dim: '#9ca3af',
  line: '#e5e7eb',
  line2: '#d1d5db',
  surface: '#ffffff',
  inset: '#f8fafc',
  primary: '#4f46e5',
  primaryHover: '#4338ca',
  selected: '#eef2ff',
  selectedBorder: '#c7d2fe',
  success: '#059669',
  successTint: '#ecfdf5',
  warning: '#b45309',
  warningTint: '#fffbeb',
  danger: '#dc2626',
  dangerTint: '#fef2f2',
  shadowCard: '0 1px 2px rgba(16, 24, 40, 0.06)',
  shadowModal: '0 12px 32px rgba(16, 24, 40, 0.12)',
} as const;

export const listeningMakerStyles = {
  panel: {
    background: listeningMakerTokens.surface,
    border: `1px solid ${listeningMakerTokens.line}`,
    borderRadius: '12px',
    boxShadow: listeningMakerTokens.shadowCard,
  } satisfies React.CSSProperties,
  strip: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.7rem',
    padding: '0.625rem 0.8125rem',
    border: `1px solid ${listeningMakerTokens.line}`,
    borderRadius: '10px',
    background: listeningMakerTokens.inset,
  } satisfies React.CSSProperties,
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '999px',
    padding: '0.25rem 0.625rem',
    fontSize: '0.71875rem',
    fontWeight: 700,
    whiteSpace: 'nowrap',
  } satisfies React.CSSProperties,
  control: {
    width: '100%',
    border: `1px solid ${listeningMakerTokens.line2}`,
    borderRadius: '8px',
    background: listeningMakerTokens.surface,
    color: listeningMakerTokens.ink,
    fontSize: '0.8125rem',
    fontWeight: 500,
  } satisfies React.CSSProperties,
  compactButton: {
    borderRadius: '999px',
    padding: '0.45rem 0.8rem',
    border: `1px solid ${listeningMakerTokens.line2}`,
    background: listeningMakerTokens.surface,
    color: listeningMakerTokens.body,
    fontSize: '0.78125rem',
    fontWeight: 700,
    cursor: 'pointer',
  } satisfies React.CSSProperties,
};
