import React from 'react';

export const studentTokens = {
    bgPage: '#f8f9fa',
    bgShell: '#f1f4f6',
    bgSurface: '#ffffff',
    bgSurfaceAlt: '#eaeff1',
    bgSurfaceStrong: '#e3e9ec',
    bgSurfaceMuted: 'rgba(241, 244, 246, 0.72)',
    textPrimary: '#2b3437',
    textBody: '#586064',
    textMuted: '#737c7f',
    textDim: '#9b9d9e',
    accent: '#4d44e3',
    accentHover: '#3f34d6',
    accentSoft: '#e2dfff',
    outlineSoft: '#abb3b7',
    borderSoft: 'rgba(171, 179, 183, 0.24)',
    borderWhisper: 'rgba(171, 179, 183, 0.12)',
    radiusSoft: 8,
    radiusPanel: 12,
    radiusPill: 999,
};

export const S: Record<string, React.CSSProperties> = {
    mobileHeader: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        height: 56,
        background: 'rgba(248, 249, 250, 0.96)',
        borderBottom: `1px solid ${studentTokens.borderWhisper}`,
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0 16px',
        zIndex: 1000,
    },
    mobileBtn: {
        background: 'transparent',
        border: 'none',
        width: 40,
        height: 40,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '1rem',
        cursor: 'pointer',
        color: studentTokens.textPrimary,
        borderRadius: studentTokens.radiusSoft,
    },
    backdrop: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(12, 15, 16, 0.24)',
        zIndex: 999,
    },
    root: {
        minHeight: '100vh',
        fontFamily: '"Inter", sans-serif',
        color: studentTokens.textPrimary,
        background: studentTokens.bgPage,
    },
    container: {
        display: 'block',
        minHeight: '100vh',
        width: '100%',
        padding: 0,
        background: studentTokens.bgPage,
    },
    bodyFrame: {
        marginLeft: 256,
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'stretch',
    },
    sidebar: {
        width: 256,
        minWidth: 0,
        padding: '32px 14px 18px 18px',
        display: 'flex',
        flexDirection: 'column',
        position: 'fixed',
        top: 0,
        left: 0,
        height: '100vh',
        overflowY: 'auto',
        background: studentTokens.bgShell,
        borderRight: `1px solid ${studentTokens.borderWhisper}`,
    },
    sidebarLogo: {
        fontSize: '0.8125rem',
        fontWeight: 800,
        color: studentTokens.textPrimary,
        marginBottom: 28,
        padding: '0 10px',
        letterSpacing: '0.16em',
        textTransform: 'uppercase',
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        padding: '10px 12px',
        borderRadius: 0,
        color: studentTokens.textMuted,
        fontWeight: 600,
        textDecoration: 'none',
        fontSize: '0.625rem',
        letterSpacing: '0.05em',
        textTransform: 'uppercase' as const,
        transition: 'background 0.15s ease, color 0.15s ease',
        cursor: 'pointer',
        border: 'none',
        textAlign: 'left',
        width: '100%',
        background: 'transparent',
    },
    navItemActive: {
        fontWeight: 600,
        color: studentTokens.accent,
        background: 'rgba(255, 255, 255, 0.5)',
        borderLeft: `2px solid ${studentTokens.accent}`,
    },
    navBadge: {
        marginLeft: 'auto',
        background: studentTokens.accent,
        color: '#faf6ff',
        fontSize: '0.625rem',
        fontWeight: 700,
        padding: '2px 6px',
        borderRadius: studentTokens.radiusPill,
    },
    joinBtn: {
        width: '100%',
        background: studentTokens.bgSurface,
        color: studentTokens.textPrimary,
        fontWeight: 700,
        padding: '11px 14px',
        borderRadius: studentTokens.radiusSoft,
        fontSize: '0.75rem',
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        border: `1px solid ${studentTokens.borderSoft}`,
        cursor: 'pointer',
        transition: 'background 0.2s ease, border-color 0.2s ease',
    },
    profileRow: {
        marginTop: 18,
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        padding: 12,
        borderRadius: studentTokens.radiusSoft,
        cursor: 'pointer',
        transition: 'background 0.15s ease',
    },
    profileAvatar: {
        width: 36,
        height: 36,
        borderRadius: '50%',
        background: studentTokens.bgSurfaceStrong,
        color: studentTokens.accent,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 700,
        flexShrink: 0,
    },
    feed: {
        width: 'min(100%, 896px)',
        maxWidth: 896,
        flex: '1 1 auto',
        margin: 0,
        background: studentTokens.bgPage,
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        minWidth: 0,
        padding: '24px 32px 48px',
    },
    feedHeader: {
        position: 'relative',
        background: 'transparent',
        borderBottom: 'none',
        padding: '8px 0 10px',
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        gap: 24,
    },
    feedHeaderTitle: {
        margin: 0,
        fontSize: '2rem',
        fontWeight: 800,
        letterSpacing: '-0.03em',
        color: studentTokens.textPrimary,
        lineHeight: 1.05,
    },
    feedHeaderText: {
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
        minWidth: 0,
    },
    feedHeaderSubtitle: {
        margin: 0,
        fontSize: '0.875rem',
        lineHeight: 1.5,
        color: studentTokens.textBody,
        maxWidth: 560,
    },
    filterBar: {
        display: 'flex',
        gap: 28,
        overflowX: 'auto',
        padding: '0 0 14px',
        marginTop: 28,
        borderBottom: `1px solid ${studentTokens.borderWhisper}`,
        background: 'transparent',
    },
    filterTab: {
        padding: '0 0 10px',
        fontWeight: 700,
        fontSize: '0.6875rem',
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        color: studentTokens.textMuted,
        cursor: 'pointer',
        border: 'none',
        background: 'transparent',
        borderBottom: '2px solid transparent',
        transition: 'color 0.15s ease, border-color 0.15s ease',
        whiteSpace: 'nowrap',
        flex: '0 0 auto',
    },
    filterTabActive: {
        color: studentTokens.accent,
        borderBottom: `2px solid ${studentTokens.accent}`,
    },
    contentPadding: {
        padding: '24px 0 0',
    },
    rightPanel: {
        width: 320,
        flex: '0 0 320px',
        minWidth: 320,
        padding: 0,
        background: studentTokens.bgSurfaceMuted,
        borderLeft: `1px solid ${studentTokens.borderWhisper}`,
    },
    rightSticky: {
        position: 'sticky',
        top: 0,
        background: 'transparent',
        minHeight: '100vh',
        padding: '32px 18px 28px',
    },
    widget: {
        background: 'transparent',
        borderRadius: 0,
        padding: 0,
        marginBottom: 0,
        border: 'none',
    },
    widgetTitle: {
        fontWeight: 700,
        fontSize: '0.625rem',
        letterSpacing: '0.16em',
        textTransform: 'uppercase',
        margin: '0 0 18px 0',
        color: studentTokens.textMuted,
    },
};
