import React from 'react';

// ─── STYLES ────────────────────────────────────────────────────────────────
// These are the design tokens defined in the Student View Design Standard v1.0.

export const S: Record<string, React.CSSProperties> = {
    // Mobile Header (Phone only)
    mobileHeader: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        height: 56,
        background: 'white',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0 16px',
        borderBottom: '1px solid #e5e7eb',
        zIndex: 1000,
    },
    mobileBtn: {
        background: 'transparent',
        border: 'none',
        width: 40,
        height: 40,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '1.25rem',
        cursor: 'pointer',
        color: '#4b5563',
    },
    backdrop: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(0,0,0,0.3)',
        zIndex: 999,
    },

    // Main Layout Wrappers
    root: {
        minHeight: '100vh',
        fontFamily: '"Inter", sans-serif',
        color: '#111827',
    },
    container: {
        display: 'flex',
        maxWidth: 1400,
        margin: '0 auto',
        minHeight: '100vh',
        justifyContent: 'center',
    },

    // Left Sidebar
    sidebar: {
        width: 256,
        flexShrink: 0,
        padding: '24px 16px',
        display: 'flex',
        flexDirection: 'column',
        position: 'sticky',
        top: 0,
        height: '100vh',
        overflowY: 'auto',
    },
    sidebarLogo: {
        fontSize: '1.25rem',
        fontWeight: 800,
        color: '#4f46e5',
        marginBottom: 32,
        padding: '0 12px',
        letterSpacing: '-0.02em',
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        padding: '10px 12px',
        borderRadius: 999,
        color: '#4b5563',
        fontWeight: 500,
        textDecoration: 'none',
        fontSize: '0.95rem',
        transition: 'all 0.15s',
        cursor: 'pointer',
        border: 'none',
        textAlign: 'left',
        width: '100%',
    },
    navItemActive: {
        fontWeight: 700,
        color: '#111827',
    },
    navBadge: {
        marginLeft: 'auto',
        background: '#ef4444',
        color: 'white',
        fontSize: '0.75rem',
        fontWeight: 700,
        padding: '2px 8px',
        borderRadius: 12,
    },
    joinBtn: {
        width: '100%',
        background: '#4f46e5',
        color: 'white',
        fontWeight: 700,
        padding: '14px 16px',
        borderRadius: 999,
        fontSize: '1.125rem',
        border: 'none',
        cursor: 'pointer',
        transition: 'background 0.2s',
        boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    },
    profileRow: {
        marginTop: 24,
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        padding: 12,
        borderRadius: 12,
        cursor: 'pointer',
        transition: 'background 0.15s',
    },
    profileAvatar: {
        width: 36,
        height: 36,
        borderRadius: '50%',
        background: '#e0e7ff',
        color: '#4f46e5',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 700,
        flexShrink: 0,
    },

    // Center Feed
    feed: {
        flex: 1,
        maxWidth: 600,
        margin: 0,
        borderLeft: '1px solid #e5e7eb',
        borderRight: '1px solid #e5e7eb',
        background: '#f9fafb',
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
    },
    feedHeader: {
        position: 'sticky',
        top: 0,
        zIndex: 10,
        background: 'rgba(255,255,255,0.92)',
        backdropFilter: 'blur(12px)',
        borderBottom: '1px solid #e5e7eb',
        padding: '16px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    feedHeaderTitle: {
        margin: 0,
        fontSize: '1.25rem',
        fontWeight: 800,
        color: '#111827',
    },
    filterBar: {
        display: 'flex',
        borderBottom: '1px solid #e5e7eb',
        background: 'white',
        padding: '0 16px',
        gap: 16,
        overflowX: 'auto',
    },
    filterTab: {
        padding: '12px 0',
        fontWeight: 500,
        fontSize: '0.9rem',
        color: '#6b7280',
        cursor: 'pointer',
        border: 'none',
        background: 'transparent',
        borderBottom: '2px solid transparent',
        transition: 'all 0.15s',
        whiteSpace: 'nowrap',
        flex: 1, // Optional: ensures filter tabs take equal space (used in records page)
    },
    filterTabActive: {
        fontWeight: 700,
        color: '#111827',
        borderBottom: '2px solid #4f46e5',
    },
    contentPadding: {
        padding: 24,
    },

    // Right Panel
    rightPanel: {
        width: 320,
        flexShrink: 0,
        padding: '24px 0 24px 32px',
    },
    rightSticky: {
        position: 'sticky',
        top: 24,
    },
    widget: {
        background: '#f9fafb',
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        border: '1px solid #e5e7eb',
    },
    widgetTitle: {
        fontWeight: 700,
        fontSize: '1.125rem',
        margin: '0 0 12px 0',
        color: '#111827',
    },
};
