export const HARNESS_CONTRACT = Object.freeze({
  name: 'luyentap-windows-arm64-harness',
  version: '3.3.0',
  protocolVersion: 1,
  dependencyCacheProtocolVersion: 2,
  defaultSnapshotTimeoutMs: 180000,
  grammar: 'node scripts/harness/run-tool.mjs <tool> <project> [...args]',
  resolutionOrder: Object.freeze(['discover', 'reuse', 'adapt', 'install', 'verify']),
  tools: Object.freeze({
    firebase: Object.freeze({
      runtime: 'windows-x64', sourceMode: 'snapshot', package: 'firebase-tools', entry: 'firebase-tools/lib/bin/firebase.js',
      capabilities: [{ kind: 'java', minimumMajor: 21, commands: ['emulators:exec', 'emulators:start'] }], rejectedCommands: ['emulators:start'],
      environmentDefaultsByCommand: { 'emulators:exec': {
        VITE_FIREBASE_API_KEY: 'harness-local-placeholder', VITE_FIREBASE_AUTH_DOMAIN: 'localhost',
        VITE_FIREBASE_DATABASE_URL: 'http://localhost', VITE_FIREBASE_PROJECT_ID: 'harness-local',
        VITE_FIREBASE_STORAGE_BUCKET: 'harness-local', VITE_FIREBASE_MESSAGING_SENDER_ID: '0', VITE_FIREBASE_APP_ID: 'harness-local',
      } },
    }),
    playwright: Object.freeze({ runtime: 'windows-x64', sourceMode: 'snapshot', package: '@playwright/test', entry: '@playwright/test/cli.js', capabilities: [{ kind: 'browser', name: 'chromium', commands: ['test', 'show-report'] }] }),
    vite: Object.freeze({ runtime: 'windows-x64', sourceMode: 'snapshot', package: 'vite', entry: 'vite/bin/vite.js', rejectedCommands: ['dev', 'serve', 'preview'], rejectEmptyCommand: true, publishedOutputsByCommand: { build: ['dist'] } }),
    'vite-node': Object.freeze({ runtime: 'windows-x64', sourceMode: 'snapshot', package: 'vite-node', entry: 'vite-node/vite-node.mjs' }),
    vitest: Object.freeze({ runtime: 'windows-x64', sourceMode: 'snapshot', package: 'vitest', entry: 'vitest/vitest.mjs', requireOneShot: true }),
    wrangler: Object.freeze({ runtime: 'wsl', sourceMode: 'live', package: 'wrangler', entry: 'wrangler/bin/wrangler.js' }),
  }),
  classifications: Object.freeze([
    'completed',
    'harness_preflight_failure',
    'harness_startup_failure',
    'harness_transport_failure',
    'zero_tests_collected',
    'product_failure',
  ]),
  remediations: Object.freeze({
    HARNESS_CONTRACT_MISMATCH: { summary: 'Use the skill and every harness file from one checkout and commit lineage.', actions: ['Restore or integrate the complete .agents/skills/run-windows-arm64-tools and scripts/harness set; never copy one runner from another worktree.'], verify: 'node scripts/harness/run-tool.mjs --contract' },
    DISPATCH_PROTOCOL_MISSING: { summary: 'Enter through the repository dispatcher instead of invoking an internal runner.', actions: ['Use run-tool.mjs with the documented tool/project grammar; internal environment payloads are harness-owned.'], verify: 'node scripts/harness/run-tool.mjs --contract' },
    X64_NODE_PREREQUISITE_MISSING: { summary: 'Find and reuse a Windows x64 Node runtime before installing another copy.', discover: ['Probe CODEX_X64_NODE, %USERPROFILE%\\Tools\\node-x64\\node.exe, PATH, and standard user/system Node locations; accept only process.arch=x64.'], reuse: ['Set CODEX_X64_NODE to a compatible discovered node.exe for the current shell.'], adapt: ['Prefer a user-local x64 Node path that leaves the ARM64 host installation unchanged.'], install: ['Only when discovery finds no compatible runtime, obtain authorization and install or unpack official Windows x64 Node outside the repository.'], verify: '& $env:CODEX_X64_NODE -p "process.platform + \' \' + process.arch"' },
    X64_NODE_ARCH_MISMATCH: { summary: 'Find an x64 Node build instead of adapting an incompatible ARM64 executable.', discover: ['Probe every known Node candidate with node -p process.arch.'], reuse: ['Point CODEX_X64_NODE at the first compatible existing x64 executable.'], adapt: ['Keep the ARM64 host Node as the normal shell default and scope x64 selection to the harness.'], install: ['Install a user-local x64 Node only if no compatible candidate exists.'], verify: '& $env:CODEX_X64_NODE -p "process.arch"' },
    PROJECT_CONTEXT_INVALID: { summary: 'Select the package directory that owns both package.json and package-lock.json.', actions: ['Pass . for the root package or an explicit nested package path; do not guess from the tool name.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    PROJECT_DEPENDENCY_MISSING: { summary: 'Make the selected project own the tool it invokes.', actions: ['Confirm the package script is intended to use the tool, then deliberately add it to that project manifest and lockfile; do not borrow root dependencies.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    PROJECT_LOCK_ENTRY_MISSING: { summary: 'Repair the selected project lockfile from its manifest.', actions: ['Regenerate only that project lockfile with the approved npm version; review the lockfile diff before retrying.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    NPM_UNAVAILABLE: { summary: 'Reuse npm shipped with the selected x64 Node before installing anything.', discover: ['Inspect the selected Node directory for node_modules\\npm\\bin\\npm-cli.js and npm.cmd.'], reuse: ['Run that npm with the selected x64 Node.'], adapt: ['Place the selected x64 Node directory first on the harness PATH only.'], install: ['Repair or replace the user-local x64 Node distribution only when it does not include npm.'], verify: '& $env:CODEX_X64_NODE "$([IO.Path]::GetDirectoryName($env:CODEX_X64_NODE))\\node_modules\\npm\\bin\\npm-cli.js" --version' },
    DEPENDENCY_INSTALL_FAILED: { summary: 'Use the preserved npm output and staging directory to repair the declared dependency set.', actions: ['Inspect the evidence and npm error first; correct the manifest/lockfile only when they are inconsistent, otherwise retry with a fresh isolated cache root.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    DEPENDENCY_CACHE_INCOMPLETE: { summary: 'Prove cache corruption with a fresh cache before removing anything.', actions: ['Set CODEX_HARNESS_ROOT to a new directory and rerun doctor; remove only the exact incomplete cache identity after validating its resolved path.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    DEPENDENCY_CACHE_IDENTITY_MISMATCH: { summary: 'Stop using the stale cache entry and rebuild the exact identity.', actions: ['Rerun with a fresh CODEX_HARNESS_ROOT, then remove only the validated mismatched cache entry.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    DEPENDENCY_LOCK_TIMEOUT: { summary: 'Determine whether another dependency installation is active or abandoned.', actions: ['Inspect running harness/npm processes and the exact lock directory; wait for an active owner, or validate the abandoned exact lock before removing it.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    NATIVE_ESBUILD_MISSING: { summary: 'Rebuild the isolated x64 cache with the lockfile’s Windows x64 optional dependencies.', actions: ['Try a fresh cache first; if it still fails, inspect the selected lockfile for @esbuild/win32-x64 before changing dependencies.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    NATIVE_ROLLDOWN_MISSING: { summary: 'Rebuild the isolated x64 cache with the Rolldown Windows x64 binding.', actions: ['Try a fresh cache first; if it still fails, inspect the selected lockfile for @rolldown/binding-win32-x64-msvc.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    NATIVE_WORKERD_MISSING: { summary: 'Rebuild the selected project cache with the Windows x64 workerd package.', actions: ['Use the Cloudflare project as <project>, try a fresh cache, and inspect its lockfile for @cloudflare/workerd-windows-64 if the failure persists.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> vitest' },
    BROWSER_RUNTIME_MISSING: { summary: 'Reuse Playwright’s compatible Chromium revision before downloading it.', discover: ['Inspect PLAYWRIGHT_BROWSERS_PATH and the selected Playwright package’s chromium.executablePath(); arbitrary system Chrome is not a compatible substitute.'], reuse: ['Use the discovered executable when its expected path exists.'], adapt: ['Preserve an existing PLAYWRIGHT_BROWSERS_PATH for the harness invocation.'], install: ['If the exact revision is absent, announce the user-cache download and run node scripts/harness/run-tool.mjs playwright <project> install chromium.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> playwright' },
    JAVA_PREREQUISITE_MISSING: { summary: 'Find and reuse JDK 21+ before installing Java.', discover: ['Probe JAVA_HOME, every java on PATH, and standard user/system JDK directories; record executable and major version.'], reuse: ['Select the first discovered Java runtime with major version 21 or newer.'], adapt: ['Set JAVA_HOME and prepend its bin directory to the harness child PATH without changing the machine configuration.'], install: ['Only when no compatible runtime exists, obtain authorization and install JDK 21+ outside the repository.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> firebase' },
    WSL_PREREQUISITE_MISSING: { summary: 'Discover the configured default WSL environment before enabling or installing one.', discover: ['Run wsl --status and probe Node in the configured default distribution.'], reuse: ['Use the existing default WSL2 distribution when its Node runtime starts successfully.'], adapt: ['If another installed distribution is intended, configure it as the default outside the harness and rerun discovery.'], install: ['Only when no usable WSL environment exists, obtain authorization for wsl --install and any required reboot.'], verify: 'wsl --status; wsl -- node -p "process.platform + \' \' + process.arch"' },
    WSL_NODE_PREREQUISITE_MISSING: { summary: 'Find Node in the configured default WSL distribution before installing it.', discover: ['Probe node in the configured default WSL distribution.'], reuse: ['Use its existing Node runtime when it starts successfully.'], adapt: ['If another installed distribution is intended, configure it as the default and rerun doctor.'], install: ['Install Node inside the configured default WSL distribution only when it has no compatible runtime.'], verify: 'wsl -- node -p "process.platform + \' \' + process.arch + \' \' + process.version"' },
    WSL_NPM_PREREQUISITE_MISSING: { summary: 'Find npm beside the selected WSL Node runtime before installing another toolchain.', discover: ['Probe npm --version in the configured default WSL distribution.'], reuse: ['Use the existing npm when it starts successfully.'], adapt: ['Repair the selected WSL Node installation or its PATH without changing repository files.'], install: ['Install npm inside the configured default WSL distribution only when discovery proves it is absent.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> wrangler' },
    WSL_WRANGLER_LOCK_UNPROVABLE: { summary: 'A WSL Wrangler cache lock cannot be proven to belong to a live or safely reclaimable harness helper.', discover: ['Inspect the exact lock or guard and its owner metadata; do not delete legacy, malformed, or unreadable locks.'], reuse: ['Use a valid cache entry when one already exists for the selected Wrangler identity.'], adapt: ['Wait for a separately verified active owner, or set CODEX_HARNESS_WSL_ROOT to a fresh absolute Linux cache path for this invocation.'], install: [], verify: 'node scripts/harness/run-tool.mjs wrangler <project> --version' },
    WSL_WRANGLER_LOCK_TIMEOUT: { summary: 'A proven live WSL Wrangler installer still owns the selected cache lock.', discover: ['Inspect the exact lock owner metadata and its live process before changing cache state.'], reuse: ['Wait for the active owner to finish and publish its immutable cache.'], adapt: ['Rerun after the live owner exits; do not remove an active lock.'], install: [], verify: 'node scripts/harness/run-tool.mjs wrangler <project> --version' },
    WSL_WRANGLER_CACHE_INVALID: { summary: 'The selected immutable WSL Wrangler cache marker does not match its required identity.', discover: ['Inspect the exact WSL cache marker and pinned version, Node ABI/architecture, npm version, source lock hash, and protocol.'], reuse: ['Use a matching immutable cache entry when one exists.'], adapt: ['Set CODEX_HARNESS_WSL_ROOT to a fresh absolute Linux cache path for this invocation.'], install: ['Install the pinned Wrangler version only into the selected fresh WSL cache root.'], verify: 'node scripts/harness/run-tool.mjs wrangler <project> --version' },
    WSL_WRANGLER_CACHE_INCOMPLETE: { summary: 'The selected WSL Wrangler cache is missing its marker or executable.', discover: ['Inspect the exact immutable WSL cache entry and preserved install staging output.'], reuse: ['Use a complete matching immutable cache entry when one exists.'], adapt: ['Set CODEX_HARNESS_WSL_ROOT to a fresh absolute Linux cache path for this invocation.'], install: ['Install the pinned Wrangler version only into the selected fresh WSL cache root.'], verify: 'node scripts/harness/run-tool.mjs wrangler <project> --version' },
    WSL_WRANGLER_INSTALL_FAILED: { summary: 'The isolated WSL npm install for the pinned Wrangler version failed.', discover: ['Read the preserved WSL npm output and staging directory for the selected cache identity.'], reuse: ['Use a complete matching immutable cache entry when one exists.'], adapt: ['Set CODEX_HARNESS_WSL_ROOT to a fresh absolute Linux cache path after diagnosing the failed staging install.'], install: ['Retry the pinned Wrangler install only after discovery records the failure cause.'], verify: 'node scripts/harness/run-tool.mjs wrangler <project> --version' },
    WSL_WRANGLER_PROTOCOL_INVALID: { summary: 'The Windows dispatcher sent an invalid WSL Wrangler payload or cache-root override.', discover: ['Inspect the base64 payload fields and CODEX_HARNESS_WSL_ROOT value.'], reuse: ['Use the repository dispatcher and the default WSL cache root when no override is required.'], adapt: ['Set CODEX_HARNESS_WSL_ROOT only to an absolute normalized Linux path, for example /tmp/codex-harness-wrangler.'], install: ['Do not install dependencies; repair the dispatcher payload or cache-root override first.'], verify: 'node scripts/harness/run-tool.mjs wrangler <project> --version' },
    LIVE_WORKLOAD_REQUIRES_CHECKOUT: { summary: 'Run watch or development commands against the active checkout.', actions: ['Use the repository dev/preview script for Vite, an explicit local watch command for Vitest, or the harness WSL path for Wrangler dev.'], verify: 'git rev-parse --show-toplevel' },
    LOCAL_DEPENDENCY_OUTSIDE_PROJECT: { summary: 'Keep file: dependencies inside the selected package boundary.', actions: ['Replace the escaping file dependency with a published/workspace dependency or select the package that actually owns it.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    EXECUTION_WORKSPACE_COLLISION: { summary: 'Retry in a new per-invocation workspace and preserve the collision evidence.', actions: ['Do not reuse or edit the collided workspace; rerun once, then treat recurrence as a harness defect.'], verify: 'node scripts/harness/run-tool.mjs <tool> <project> [...args]' },
    SOURCE_MIRROR_FAILED: { summary: 'Resolve the reported copy error without changing repository dependencies.', actions: ['Inspect the exact robocopy error, close locks on the per-run destination, and retry; keep the source checkout unchanged.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    TOOL_ENTRYPOINT_MISSING: { summary: 'Rebuild the isolated cache and verify the selected package lock entry.', actions: ['Use a fresh cache; if the entry remains absent, repair the selected manifest/lockfile rather than using repository node_modules.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
    TOOL_UNSUPPORTED: { summary: 'Choose a tool declared by the executable harness contract.', actions: ['Read tools from --contract; add a new tool only as an intentional contract, runner, skill, and test change.'], verify: 'node scripts/harness/run-tool.mjs --contract' },
    OUTPUT_MISSING: { summary: 'Reconcile the successful build command with its declared output directory.', actions: ['Inspect the selected project build configuration and snapshot output; correct the contract only when the project intentionally writes elsewhere.'], verify: 'node scripts/harness/run-tool.mjs <tool> <project> [...args]' },
    OUTPUT_PATH_INVALID: { summary: 'Keep published build outputs inside the selected project.', actions: ['Correct the declarative output path; never publish a snapshot path that escapes the project root.'], verify: 'node scripts/harness/run-tool.mjs --contract' },
    TOOL_TIMEOUT: { summary: 'Narrow the command and determine whether startup, product work, or transport consumed the timeout.', actions: ['Read partial tool output and evidence, rerun the smallest affected file, and increase CODEX_HARNESS_TIMEOUT_MS only when the expected duration is understood.'], verify: 'node scripts/harness/run-tool.mjs <tool> <project> [...args]' },
    ZERO_TESTS_COLLECTED: { summary: 'Confirm the intended test path and runner configuration collect real tests.', actions: ['Run the smallest intended test file explicitly and inspect include/exclude/config rules; do not count definition-only success as test execution.'], verify: 'node scripts/harness/run-tool.mjs vitest <project> run <test-file>' },
    TOOL_STARTUP_FAILED: { summary: 'Repair the reported native or process startup condition before inspecting product assertions.', actions: ['Use doctor for the same project/tool, then rerun the smallest command after doctor passes.'], verify: 'node scripts/harness/run-tool.mjs --doctor <project> <tool>' },
  }),
});

export const toolNames = Object.freeze(Object.keys(HARNESS_CONTRACT.tools));

export function wranglerDependencyCacheIdentity({ version, nodeAbi, architecture, npmVersion, sourceLockSha256, dependencyCacheProtocolVersion = HARNESS_CONTRACT.dependencyCacheProtocolVersion }) {
  return `${version}-node${nodeAbi}-${architecture}-npm${npmVersion}-lock${sourceLockSha256.slice(0, 12)}-protocol${dependencyCacheProtocolVersion}`;
}

export function remediationFor(code, project = '<project>', tool = '<tool>') {
  const remediation = HARNESS_CONTRACT.remediations[code];
  if (!remediation) return null;
  const replace = (value) => value.replaceAll('<project>', project).replaceAll('<tool>', tool);
  const stages = {};
  for (const stage of HARNESS_CONTRACT.resolutionOrder) {
    const values = stage === 'verify' ? [remediation.verify] : (remediation[stage] ?? (stage === 'adapt' ? remediation.actions : []));
    stages[stage] = values.filter(Boolean).map(replace);
  }
  return { code, summary: replace(remediation.summary), stages };
}
