/**
 * Feature Registry — Central registry of all tracked features
 * PRD-0037: Production Reporting & Observability System
 *
 * Exports:
 * - FEATURE_REGISTRY: array of all feature definitions
 * - resolveFeatureFromRoute(pathname): maps URL → feature ID
 * - validateFeatureId(id): checks if a feature ID is registered
 */

import { ROUTES } from '../constants/routes';

// ─── Types ──────────────────────────────────────────────────────────────────

export interface FeatureDefinition {
  id: string;
  name: string;
  routes: string[];
  actions: string[];
  description: string;
}

export const FEATURE_IDS = {
  adminPanel: 'adminPanel',
  antiCheat: 'antiCheat',
  classes: 'classes',
  courses: 'courses',
  grading: 'grading',
  homework: 'homework',
  readingV2Studio: 'readingV2Studio',
  results: 'results',
  studentDashboard: 'studentDashboard',
  testTaking: 'testTaking',
  testCreation: 'testCreation',
} as const;

// ─── Registry ───────────────────────────────────────────────────────────────

export const FEATURE_REGISTRY: FeatureDefinition[] = [
  {
    id: FEATURE_IDS.testTaking,
    name: 'Test Taking',
    routes: [
      '/student-test/:sessionCode',
      '/student/practice/:materialId',
      '/student/solo-test/:materialId',
      '/student/homework/:homeworkId/test',
      '/__smoke/book-runtime',
    ],
    actions: [
      'startTest',
      'submitAnswer',
      'nextQuestion',
      'previousQuestion',
      'finishTest',
      'timeOut',
      'abandonTest',
      'openQuestionSheet',
      'closeQuestionSheet',
      'openReviewSummary',
      'closeReviewSummary',
      'openOverflowMenu',
      'closeOverflowMenu',
      'openTextSizeControl',
      'adjustTextSize',
      'closeTextSizeControl',
      'openInstructions',
      'closeInstructions',
      'leaveTest',
      'jumpToQuestion',
      'switchListeningPart',
      'switchListeningImage',
      'openSubmitSheet',
      'confirmSubmit',
      'launchReadingV2Runtime',
      'launchReadingPassageHomeworkRuntime',
      'readingV2LaunchBlocked',
      'submitReadingV2Attempt',
      'teacher_materials_reading_passage_homework_launched',
      'teacher_materials_reading_passage_homework_submitted',
      'reading_v2_assignment_payload_missing',
      'reading_v2_frozen_runtime_launched',
      'launchBookRuntime',
      'bookRuntimeLaunchBlocked',
      'bookRuntimeReturn',
      'bookRuntimePageGroupSelected',
      'bookRuntimeComponentSelected',
      'bookRuntimeComponentPageChanged',
      'bookRuntimeActivitySelected',
      'bookRuntimeActivityNavigated',
      'bookRuntimePdfFocused',
      'bookRuntimeSplitRestored',
      'bookRuntimeNavigatorToggled',
      'bookRuntimeTabSwitched',
      'bookRuntimeResponseChanged',
      'bookRuntimeAutosaveRetry',
      'bookRuntimeAutosaveReload',
      'bookRuntimeAutosaveDiscard',
      'bookRuntimeMetricRecorded',
      'bookRuntimeSubmitActivity',
    ],
    description: 'Student test-taking and practice sessions',
  },
  {
    id: FEATURE_IDS.testCreation,
    name: 'Test Creation',
    routes: [
      '/teacher/test/create',
      '/teacher/test/create-standalone',
      '/teacher/test/review/:draftId',
      '/teacher/thcs-test/create',
      '/teacher/thcs-test/edit/:draftId',
      '/teacher/writing-test/create',
      '/teacher/writing-test/edit/:draftId',
      '/__smoke/book-editor',
    ],
    actions: [
      'createTest',
      'changeMaterialsViewMode',
      'editTest',
      'toggleVisibility',
      'saveDraft',
      'publishTest',
      'selectListeningSkill',
      'startListeningCreationMode',
      'listeningAuthoringStepNext',
      'listeningAuthoringStepBack',
      'listeningSectionAdded',
      'listeningSectionRemoved',
      'listeningImageSectionSelected',
      'listeningQuestionImagePasteRequested',
      'listeningQuestionImageUploadRequested',
      'listeningPublishReadinessChecked',
      'listeningPublishReadinessFailed',
      'discardListeningDraft',
      'recoverListeningConflict',
      'listeningDuplicateActionBlocked',
      'archiveListeningPublishedVersion',
      'restoreListeningDraft',
      'listeningAutosaveFailure',
      'listeningRevisionCreated',
      'listeningCommitFailure',
      'listeningOrphanGrowthObserved',
      'listeningLegacyTransition',
      'deleteTest',
      'openReadingPassage',
      'editReadingPassage',
      'assignReadingPassageHomework',
      'assignSelectedReadingPassages',
      'assignSelectedMaterials',
      'deleteSelectedMaterials',
      'archiveSelectedMaterials',
      'createReadingFullTestFromSelectedPassages',
      'archiveReadingPassage',
      'master_delete_requested',
      'master_linked_passages_remove_requested',
      'teacher_materials_reading_master_removed',
      'teacher_materials_reading_master_and_linked_passages_removed',
      'changeReadingPassageScope',
      'teacher_materials_tab_changed',
      'teacher_materials_test_type_filter_selected',
      'teacher_materials_test_type_filter_cleared',
      'teacher_materials_test_type_preferences_opened',
      'teacher_materials_test_type_preferences_saved',
      'teacher_materials_book_create_opened',
      'teacher_materials_book_mode_selected',
      'teacher_materials_book_created',
      'teacher_materials_book_successor_opened',
      'teacher_materials_book_successor_canceled',
      'teacher_materials_book_successor_created',
      'teacher_materials_book_successor_failed',
      'teacher_materials_book_assembly_mapping_revision_opened',
      'teacher_materials_book_assembly_mapping_revision_changed',
      'teacher_materials_book_assembly_mapping_revision_previewed',
      'teacher_materials_book_assembly_mapping_revision_published',
      'teacher_materials_book_assembly_mapping_revision_canceled',
      'teacher_materials_book_assembly_mapping_revision_failed',
      'teacher_materials_book_updated',
      'teacher_materials_book_public_review_requested',
      'teacher_materials_book_editor_opened',
      'teacher_materials_book_cover_uploaded',
      'teacher_materials_reading_passage_assigned',
      'teacher_materials_reading_passage_set_assigned',
      'teacher_materials_reading_passage_archived',
      'openCreateBookModal',
      'createBook',
      'openBook',
      'editBookMetadata',
      'saveBookStructure',
      'assignBookMaterialRef',
      'teacher_materials_book_node_added',
      'teacher_materials_book_node_reordered',
      'teacher_materials_book_node_deleted',
      'teacher_materials_book_material_attached',
      'teacher_materials_book_material_removed',
      'teacher_materials_book_ref_repaired_existing',
      'teacher_materials_book_ref_removed',
      'teacher_materials_book_ref_restore_started',
      'teacher_materials_book_assembly_strategy_changed',
      'teacher_materials_book_assembly_strategy_migration_requested',
      'teacher_materials_book_assembly_strategy_migration_started',
      'teacher_materials_book_assembly_strategy_migration_prepared',
      'teacher_materials_book_assembly_strategy_migration_confirmed',
      'teacher_materials_book_assembly_strategy_migration_canceled',
      'teacher_materials_book_assembly_strategy_migration_failed',
      'teacher_materials_book_assembly_source_bound',
      'teacher_materials_book_assembly_source_owner_changed',
      'teacher_materials_book_assembly_source_reordered',
      'teacher_materials_book_assembly_source_removed',
      'teacher_materials_book_assembly_page_group_mapped',
      'teacher_materials_book_assembly_activity_slot_reordered',
      'teacher_materials_book_assembly_saved',
      'teacher_materials_book_assembly_conflict_reloaded',
      'teacher_materials_book_assembly_conflict_retry_selected',
      'teacher_materials_book_assembly_local_discarded',
      'teacher_materials_book_assembly_document_previewed',
      'teacher_materials_book_assembly_mapping_viewer_page_selected',
      'teacher_materials_book_assembly_unit_prompt_copied',
      'teacher_materials_book_assembly_unit_prompt_manual_copy_shown',
      'teacher_materials_book_assembly_unit_import_started',
      'teacher_materials_book_assembly_unit_import_staged',
      'teacher_materials_book_assembly_unit_import_failed',
      'teacher_materials_book_assembly_unit_import_canceled',
      'teacher_materials_book_assembly_reconciliation_repair_applied',
      'teacher_materials_book_assembly_reconciliation_repair_failed',
      'teacher_materials_book_assembly_reconciliation_teacher_choice_recorded',
      'teacher_materials_book_assembly_candidate_preview_opened',
      'teacher_materials_book_assembly_candidate_preview_response_changed',
      'teacher_materials_book_assembly_candidate_preview_activity_selected',
      'teacher_materials_book_assembly_candidate_preview_closed',
      'reading_passage_duplicate_warning_shown',
      'reading_passage_duplicate_use_existing',
      'reading_passage_duplicate_restore_and_use',
      'reading_passage_duplicate_create_new_anyway',
      'reading_passage_duplicate_audit_failed',
      'archiveBook',
      'changeBookScope',
      'uploadDocument',
      'parseDocument',
      'aiGenerate',
      'selectReadingV2Skill',
      'startReadingV2Blank',
      'startReadingV2Import',
      'startReadingV2AutoImport',
      'startReadingV2ExistingPassages',
      'copyReadingV2ImportPrompt',
      'clearReadingV2ImportSetup',
      'parseReadingV2ImportSetup',
      'clearReadingV2AutoImportSetup',
      'submitReadingV2AutoImport',
      'completeReadingV2AutoImport',
      'failReadingV2AutoImport',
      'toggleTableRepairMode',
      'addTableRow',
      'deleteTableRow',
      'mergeTableCell',
      'splitTableCell',
      'changeTableCellRole',
      'insertTableBlankAnchor',
      'removeTableBlankAnchor',
      'acknowledgeGroupedWarning',
      'reRunGroupedParse',
      'discardGroupedCandidate',
      'reclassifyGroupedCandidate',
    ],
    description: 'Teacher test creation and editing workflows',
  },
  {
    id: FEATURE_IDS.readingV2Studio,
    name: 'Reading V2 Studio',
    routes: [
      '/teacher/reading-v2/create',
      '/teacher/reading-v2/import',
      '/teacher/reading-v2/drafts/:draftId',
      '/teacher/reading-v2/materials/:materialId/revise',
      '/teacher/materials/books/:bookId',
      '/__smoke/book-assembly',
      '/__smoke/book-assembly-mapping-revision',
      '/__smoke/book-assembly-activity-revision',
    ],
    actions: [
      'openStudio',
      'startBlankMaterial',
      'startImportMaterial',
      'startAutoImportMaterial',
      'resumeDraft',
      'revisePublishedMaterial',
      'duplicateMaterial',
      'extract',
      'metadataEdit',
      'saveDraft',
      'answerKeyEdit',
      'settingsEdit',
      'passageEditorAction',
      'validate',
      'preview',
      'publish',
      'toolbarMoreMenu',
      'discard',
      'operationalStateAction',
      'inspectProvenance',
      'inspectImportEvidence',
      'jumpImportDiagnostic',
      'questionLinkNavigate',
      'questionLinkRepair',
      'reviewIssuesOpen',
      'reviewIssuesClose',
      'reviewIssueNavigate',
      'copyParsingDiagnostics',
      'toggleImportReviewDetails',
      'importMaterial',
      'canonicalAnchorGuardFailed',
      'duplicateStructuredLayoutQuestion',
      'structuredLayoutAnchorCardinalityMismatch',
      'studioImportCandidateRejected',
      'publishCanonicalValidationBlocked',
      'passageExtractionCanonicalValidationBlocked',
      'backfillCanonicalValidationBlocked',
      'tableCompletionEdit',
      'openModal',
      'openFromTeacherLobbyCard',
      'openFromTeacherLobbyDraft',
      'openCreateBookModal',
      'createBook',
      'openBook',
      'book_source_pdf_inspection_started',
      'book_source_pdf_inspection_completed',
      'book_source_pdf_inspection_failed',
      'book_source_pdf_inspection_canceled',
      'book_source_pdf_inspection_retried',
      'book_source_upload_started',
      'book_source_upload_byte_retry_started',
      'book_source_upload_completion_retry_started',
      'book_source_upload_canceled',
      'book_source_upload_cancel_request_failed',
      'book_source_upload_restored',
      'book_source_upload_verified',
      'book_source_upload_failed',
      'editBookMetadata',
      'saveBookStructure',
      'assignBookMaterialRef',
      'teacher_materials_book_updated',
      'teacher_materials_book_public_review_requested',
      'teacher_materials_book_editor_opened',
      'teacher_materials_book_cover_uploaded',
      'teacher_materials_reading_passage_assigned',
      'teacher_materials_book_node_added',
      'teacher_materials_book_node_reordered',
      'teacher_materials_book_node_deleted',
      'teacher_materials_book_material_attached',
      'teacher_materials_book_material_removed',
      'teacher_materials_book_ref_repaired_existing',
      'teacher_materials_book_ref_removed',
      'teacher_materials_book_ref_restore_started',
      'teacher_materials_book_assembly_strategy_changed',
      'teacher_materials_book_assembly_strategy_migration_requested',
      'teacher_materials_book_assembly_strategy_migration_started',
      'teacher_materials_book_assembly_strategy_migration_prepared',
      'teacher_materials_book_assembly_strategy_migration_confirmed',
      'teacher_materials_book_assembly_strategy_migration_canceled',
      'teacher_materials_book_assembly_strategy_migration_failed',
      'teacher_materials_book_assembly_source_bound',
      'teacher_materials_book_assembly_source_owner_changed',
      'teacher_materials_book_assembly_source_reordered',
      'teacher_materials_book_assembly_source_removed',
      'teacher_materials_book_assembly_page_group_mapped',
      'teacher_materials_book_assembly_activity_slot_reordered',
      'teacher_materials_book_assembly_saved',
      'teacher_materials_book_assembly_conflict_reloaded',
      'teacher_materials_book_assembly_conflict_retry_selected',
      'teacher_materials_book_assembly_local_discarded',
      'teacher_materials_book_assembly_document_previewed',
      'teacher_materials_book_assembly_mapping_viewer_page_selected',
      'teacher_materials_book_assembly_unit_prompt_copied',
      'teacher_materials_book_assembly_unit_prompt_manual_copy_shown',
      'teacher_materials_book_assembly_unit_import_started',
      'teacher_materials_book_assembly_unit_import_staged',
      'teacher_materials_book_assembly_unit_import_failed',
      'teacher_materials_book_assembly_unit_import_canceled',
      'teacher_materials_book_assembly_reconciliation_repair_applied',
      'teacher_materials_book_assembly_reconciliation_repair_failed',
      'teacher_materials_book_assembly_reconciliation_teacher_choice_recorded',
      'teacher_materials_book_assembly_activity_revision_prompt_copied',
      'teacher_materials_book_assembly_activity_revision_imported',
      'teacher_materials_book_assembly_activity_revision_previewed',
      'teacher_materials_book_assembly_activity_revision_published',
      'teacher_materials_book_assembly_activity_revision_conflict_reloaded',
      'teacher_materials_book_assembly_activity_revision_discarded',
      'teacher_materials_book_assembly_activity_revision_failed',
      'teacher_materials_book_replacement_plan_opened',
      'teacher_materials_book_replacement_plan_created',
      'teacher_materials_book_replacement_plan_reviewed',
      'teacher_materials_book_replacement_plan_canceled',
      'teacher_materials_book_replacement_plan_replanned',
      'teacher_materials_book_replacement_plan_expired',
      'teacher_materials_book_replacement_plan_handoff_ready',
      'teacher_materials_book_replacement_plan_failed',
      'reading_passage_duplicate_warning_shown',
      'reading_passage_duplicate_use_existing',
      'reading_passage_duplicate_restore_and_use',
      'reading_passage_duplicate_create_new_anyway',
      'archiveBook',
      'changeBookScope',
      'exitStudio',
      'reading_v2_master_edit_opened',
      'reading_v2_master_metadata_saved',
      'reading_v2_master_passage_reordered',
      'reading_v2_master_passage_added',
      'reading_v2_master_passage_removed',
      'reading_v2_master_passage_clone_requested',
      'reading_v2_master_passage_cloned',
      'reading_v2_master_clone_requested',
      'reading_v2_master_publish_submitted',
      'reading_v2_master_publish_completed',
      'reading_v2_master_publish_failed',
      'reading_v2_library_passage_clone_requested',
      'reading_v2_library_passage_cloned',
      'reading_v2_master_broken_refs_viewed',
      'reading_v2_master_ref_repair_started',
      'reading_v2_master_ref_repaired_existing',
      'reading_v2_master_ref_removed',
      'reading_v2_master_ref_remake_started',
      'reading_v2_master_repair_publish_submitted',
      'reading_v2_single_passage_version_published',
      'reading_v2_update_references_opened',
      'reading_v2_update_references_skipped',
      'reading_v2_update_references_submitted',
      'reading_v2_update_references_partial_failed',
      'startReadingV2ExistingPassages',
    ],
    description: 'Reading V2 studio entry and revision boundaries',
  },
  {
    id: FEATURE_IDS.homework,
    name: 'Homework',
    routes: [
      '/teacher/homework',
      '/teacher/homework/:homeworkId',
      '/teacher/homework/student/:studentId',
      '/student/homework',
      '/student/homework/:homeworkId',
      '/__smoke/book-homework-preview',
      ROUTES.BOOK_HOMEWORK_COMPLETION_SMOKE,
    ],
    actions: [
      'assignHomework',
      'submitHomework',
      'reviewHomework',
      'viewIntegrityDetails',
      'archiveHomework',
      'bulkAssign',
      'filterHomeworkList',
      'startHomework',
      'continueHomework',
      'viewHomeworkResult',
      'closeHomeworkResult',
      'refreshHomeworkList',
      'reading_v2_master_homework_assigned',
      'reading_v2_assignment_refresh_opened',
      'reading_v2_assignment_refresh_submitted',
      'reading_v2_assignment_refresh_blocked_started',
      'bookHomeworkPreviewOpened',
      'bookHomeworkTargetSelected',
      'bookHomeworkPolicyChanged',
      'bookHomeworkActivityPolicyChanged',
      'bookHomeworkScheduleIntent',
      'bookHomeworkForkRequested',
      'bookHomeworkPreviewConfirmed',
      'bookHomeworkPreviewCanceled',
      'bookHomeworkProgressBack',
      'bookHomeworkProgressRetry',
      'bookHomeworkCompletionSmokeSubjectiveSubmitted',
      'bookHomeworkCompletionSmokeScoredSubmitted',
      'bookActivityGradingOpened',
      'bookActivityEvaluationLoaded',
      'bookActivityGradeSubmitted',
      'bookActivityRegradeSubmitted',
      'bookActivityEvaluationConflict',
      'bookActivityEvaluationRetried',
      'bookActivityIntegrityOpened',
      'bookActivityIntegrityLoaded',
      'bookActivityIntegrityRetried',
      'bookActivityIntegrityClosed',
    ],
    description: 'Homework assignment and management',
  },
  {
    id: FEATURE_IDS.courses,
    name: 'Courses',
    routes: [
      '/teacher/courses',
      '/teacher/courses/:courseId',
      '/student/courses',
      '/student/courses/:courseId',
      '/student/courses/catalog',
    ],
    actions: [
      'createCourse',
      'editCourse',
      'enrollStudent',
      'syncCourse',
      'addMaterial',
      'openCourseBookPlacement',
      'placeCourseBook',
      'revokeCourseBook',
      'prepareCourseBook',
      'addAnnouncement',
    ],
    description: 'Course management for teachers and students',
  },
  {
    id: FEATURE_IDS.classes,
    name: 'Classes',
    routes: [
      '/teacher/classes',
      '/teacher/classes/:classId',
      '/student/classes/:classId',
    ],
    actions: [
      'createClass',
      'editClass',
      'addStudent',
      'removeStudent',
      'approveStudent',
      'rejectStudent',
      'viewHomeworkTab',
      'openHomeworkCreateModal',
      'openHomeworkDetail',
      'openHomeworkDashboard',
    ],
    description: 'Class management and viewing',
  },
  {
    id: 'liveSessions',
    name: 'Live Sessions',
    routes: [
      '/teacher-test/:sessionCode',
      '/student-wait/:gameSessionId',
    ],
    actions: [
      'createSession',
      'joinSession',
      'startSession',
      'endSession',
      'forceSubmitStudent',
      'viewIntegrityDetails',
      'refreshIntegrityLogs',
      'resetStudentSubmission',
      'listeningLive.pauseAudio',
      'listeningLive.resumeAudio',
      'listeningLive.seekAudio',
      'listeningLive.skipSection',
      'listeningLive.changeSpeed',
    ],
    description: 'Real-time test sessions',
  },
  {
    id: FEATURE_IDS.antiCheat,
    name: 'Anti-Cheat',
    routes: [],
    actions: [
      'initializeProtection',
      'restoreIntegrityState',
      'recordViolation',
      'recordSignal',
      'escalateWarning',
      'triggerAutoSubmit',
      'flushIntegrityLogs',
      'persistIntegritySnapshot',
      'persistSessionIntegrity',
      'persistHomeworkIntegrity',
      'handleTeacherForceSubmit',
      'blockHomeworkEntry',
    ],
    description:
      'High-signal runtime telemetry for integrity detection, persistence, and teacher-triggered anti-cheat flows',
  },
  {
    id: FEATURE_IDS.grading,
    name: 'Grading',
    routes: [
      '/teacher/grading',
      '/teacher/grading/writing',
      '/teacher/grading/writing/:submissionId',
    ],
    actions: [
      'openSubmission',
      'startRegrade',
      'acquireLock',
      'lockExpired',
      'discardDraftTakeover',
      'cancelDraftTakeover',
      'saveDraft',
      'submitGrading',
      'cancelRegrade',
      'switchTask',
      'switchTab',
      'formatFeedback',
      'toggleOriginalView',
      'addComment',
      'addCorrection',
      'editCorrection',
      'deleteCorrection',
      'resolveComment',
      'deleteComment',
      'recoverComment',
      'useQuickComment',
      'viewSuggestions',
      'openSuggestionReview',
      'closeSuggestionReview',
      'generateSuggestions',
      'generateMoreSuggestions',
      'reloadSuggestions',
      'approveSuggestion',
      'dismissSuggestion',
      'restoreSuggestion',
      'showSuggestionLeaveWarning',
      'discardChanges',
      'cancelLeave',
      'bulkGrade',
    ],
    description: 'Teacher grading workflows',
  },
  {
    id: 'aiOperations',
    name: 'AI Operations',
    routes: [],
    actions: [
      'generateFeedback',
      'parseDocument',
      'classifyQuestion',
      'generateQuiz',
      'aiRetry',
      'aiFailure',
    ],
    description: 'AI-powered operations across features',
  },
  {
    id: 'authentication',
    name: 'Authentication',
    routes: ['/'],
    actions: [
      'login',
      'logout',
      'register',
      'resetPassword',
      'toggleDevQuickLogin',
      'roleSwitch',
    ],
    description: 'User authentication and authorization',
  },
  {
    id: FEATURE_IDS.adminPanel,
    name: 'Admin Panel',
    routes: ['/admin/*'],
    actions: [
      'viewDashboard',
      'manageUsers',
      'manageClasses',
      'viewBackups',
      'triggerBackup',
      'updateReportingMode',
      'toggleReportingCategory',
      'toggleReportingAdvancedPanel',
      'saveReportingRetention',
      'purgeReports',
      'viewReports',
      'switchTestTypeSettingsSection',
      'createTestType',
      'editTestType',
      'deactivateTestType',
      'reorderTestType',
      'toggleAllowedMaterialKind',
      'retryTestTypeAdminLoad',
      'switchPublicBookReviewsSettingsSection',
      'retryPublicBookReviewQueue',
      'approvePublicBookReview',
      'rejectPublicBookReview',
      'returnPublicBookToPrivate',
      'adminLogout',
      'navigateAdminSection',
      'refreshSessions',
      'openCreateSession',
      'closeCreateSession',
      'createSession',
      'joinSession',
      'endSession',
      'deleteSession',
      'extendSession',
    ],
    description: 'Super admin management panel',
  },
  {
    id: FEATURE_IDS.studentDashboard,
    name: 'Student Dashboard',
    routes: [
      '/student',
      '/student/dashboard',
    ],
    actions: [
      'filterFeed',
      'searchFeed',
      'toggleUnreadFeed',
      'loadMoreFeed',
      'markAllFeedRead',
      'openJoinClassModal',
      'closeJoinClassModal',
      'submitJoinClass',
      'joinLiveSession',
      'joinPublicSession',
      'expandPublicSessions',
      'openAcademicHistory',
      'openFeedResult',
      'openSessionNotification',
      'openFeedLink',
      'openHomeworkList',
      'openHomeworkAssignment',
      'closeResultSlidePanel',
    ],
    description: 'Student dashboard feed, activity, live sessions, and join-class workflows',
  },
  {
    id: 'academicRecords',
    name: 'Academic Records',
    routes: ['/student/academic-record'],
    actions: [
      'viewRecords',
      'viewFeedback',
      'requestFeedback',
      'openSlidePanel',
      'closeSlidePanel',
      'switchResultTab',
      'selectAttempt',
      'jumpToQuestion',
      'retryAiFeedback',
      'returnToDashboard',
    ],
    description: 'Student academic record viewing',
  },
  {
    id: FEATURE_IDS.results,
    name: 'Results',
    routes: [
      '/guest-results',
      '/teacher/results',
      '/teacher/student/:studentId/history',
      '/teacher-test-results/:sessionCode',
      '/student-test-results/:sessionCode',
      '/student/results/:sessionCode',
      '/submission-complete',
      '/result/:resultId',
      '/profile/complete',
    ],
    actions: [
      'viewResults',
      'viewIntegrityDetails',
      'generateFeedback',
      'viewQuestion',
      'openReadingV2Review',
      'teacher_materials_reading_passage_result_viewed',
      'reading_v2_frozen_result_review_opened',
      'submitReadingV2Feedback',
      'createReadingV2Regrade',
      'readingV2OperationalError',
      'toggleSessionDetails',
      'exportResultsCsv',
      'exportResultsPdf',
      'openStudentHistory',
      'markResultReviewed',
      'openWritingGrading',
      // PRD-0039 Task 9.14: Slide panel actions
      'openSlidePanel',
      'closeSlidePanel',
      'switchResultTab',
      'selectAttempt',
      'jumpToQuestion',
      'retryAiFeedback',
      'returnToDashboard',
      'printWritingResults',
      'printResults',
      'switchWritingMarkupMode',
      'toggleWritingCriteriaFeedback',
      'bookActivityResultRetried',
    ],
    description: 'Test result viewing',
  },
  {
    id: 'feedback',
    name: 'Feedback',
    routes: [],
    actions: [
      'viewFeedback',
      'submitFeedback',
    ],
    description: 'Session feedback collection and viewing',
  },
  {
    id: 'profile',
    name: 'Profile',
    routes: ['/profile'],
    actions: [
      'editProfile',
      'changePassword',
      'updateAvatar',
    ],
    description: 'User profile management',
  },
  {
    id: 'materials',
    name: 'Materials',
    routes: [
      '/material/:materialId',
      ROUTES.MATERIAL_UNAVAILABLE,
      '/student/library',
    ],
    actions: [
      'viewMaterial',
      'searchMaterials',
      'startPractice',
      'materialUnavailableNoticeViewed',
      'materialUnavailableNoticeReturn',
    ],
    description: 'Material browsing and library access',
  },
  {
    id: 'sessions',
    name: 'Session Management',
    routes: ['/sessions'],
    actions: [
      'viewSessions',
      'archiveSession',
      'deleteSession',
    ],
    description: 'Teacher session management',
  },
  // DEVELOPER NOTE: When adding a new feature, also:
  // 1. Add a new entry here with id, name, routes, actions, description
  // 2. Add the useFeatureTracking hook call in the page component
  // 3. Add trackAction calls for user-facing actions
  // 4. Update documentation/rules/observability.md if needed
];

// ─── Route Resolution ─────────────────────────────────────────────────────

/**
 * Resolve a pathname to a feature ID from the registry.
 * Returns null if no match found.
 */
export function resolveFeatureFromRoute(pathname: string): string | null {
  for (const feature of FEATURE_REGISTRY) {
    for (const route of feature.routes) {
      // Special case for /admin/* wildcard
      if (route === '/admin/*') {
        if (pathname.startsWith('/admin/')) {
          return feature.id;
        }
        continue;
      }

      // Convert :param segments to regex wildcards
      const regexStr = '^' + route.replace(/:[^/]+/g, '[^/]+') + '$';
      try {
        const regex = new RegExp(regexStr);
        if (regex.test(pathname)) {
          return feature.id;
        }
      } catch {
        // Invalid regex — skip this route
      }
    }
  }
  return null;
}

/**
 * Validate that a feature ID exists in the registry.
 * In development, logs a warning for unknown IDs.
 */
export function validateFeatureId(featureId: string): boolean {
  const exists = FEATURE_REGISTRY.some((f) => f.id === featureId);
  if (!exists && import.meta.env.DEV) {
    console.warn('[FeatureRegistry] Unknown feature ID: ' + featureId);
  }
  return exists;
}
