import type { ReadingV2StoragePathClass } from './readingV2StoragePaths.service';
import { readingV2StoragePaths } from './readingV2StoragePaths.service';

export type ReadingV2OperationalRole = 'teacher-owner' | 'admin' | 'student' | 'system';
export type ReadingV2ReadWriteMode = 'read' | 'write' | 'read-write' | 'append-only';
export type ReadingV2FrequencyClass = 'low' | 'medium' | 'high';
export type ReadingV2AtomicityDecision = 'single-write' | 'transaction-required' | 'batch-required';

export interface ReadingV2OperationalMatrixEntry {
  readonly pathClass: ReadingV2StoragePathClass;
  readonly samplePath: string;
  readonly owningService: string;
  readonly consumingSurface: string;
  readonly allowedRoles: readonly ReadingV2OperationalRole[];
  readonly readWriteMode: ReadingV2ReadWriteMode;
  readonly queryPattern: string;
  readonly indexRequirement: string;
  readonly frequencyClass: ReadingV2FrequencyClass;
  readonly retentionDeletionBehavior: string;
  readonly projectionSafetyRule: string;
  readonly forbiddenFields: readonly string[];
  readonly atomicityDecision: ReadingV2AtomicityDecision;
}

export const READING_V2_FORBIDDEN_STUDENT_FIELDS = [
  'answerKeys',
  'acceptableAnswers',
  'scoringRule',
  'authorDiagnostics',
  'importEvidence',
  'hiddenProvenance',
  'teacherOnlyReview',
] as const;

export const READING_V2_OPERATIONAL_MATRIX = [
  {
    pathClass: 'drafts',
    samplePath: readingV2StoragePaths.drafts('draft-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Reading V2 Studio',
    allowedRoles: ['teacher-owner', 'admin'],
    readWriteMode: 'read-write',
    queryPattern: 'ownerId plus state list for Studio draft resume',
    indexRequirement: 'ownerId/state composite index before remote implementation',
    frequencyClass: 'high',
    retentionDeletionBehavior: 'discard marks draft discarded; hard delete is retention task only',
    projectionSafetyRule: 'canonical authoring data only; never student-readable',
    forbiddenFields: [],
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'passageAssets',
    samplePath: readingV2StoragePaths.passageAssets('asset-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Studio stimulus search and Material Profile dependency display',
    allowedRoles: ['teacher-owner', 'admin'],
    readWriteMode: 'read-write',
    queryPattern: 'topic, owner, governance state',
    indexRequirement: 'topic/state/owner search index',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'retired blocks new use but preserves history',
    projectionSafetyRule: 'asset metadata is packaging data; raw asset is not a student launch unit',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'passageAssetVersions',
    samplePath: readingV2StoragePaths.passageAssetVersions('asset-1', 'v1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Studio stimulus editor and publish pipeline',
    allowedRoles: ['teacher-owner', 'admin'],
    readWriteMode: 'append-only',
    queryPattern: 'assetId plus versionId',
    indexRequirement: 'assetId/version lookup',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'versions are immutable once published dependents exist',
    projectionSafetyRule: 'student projections receive sanitized copied stimulus content only',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'taskGroupMaterials',
    samplePath: readingV2StoragePaths.taskGroupMaterials('material-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Teacher Lobby cards, Material Profile, assignment pickers',
    allowedRoles: ['teacher-owner', 'admin'],
    readWriteMode: 'read-write',
    queryPattern: 'owner, state, officialTaskType, engineeringFamily',
    indexRequirement: 'owner/state/family/type index',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'archive/retire preserves result references',
    projectionSafetyRule: 'packaging metadata only; canonical task truth stays in snapshots/drafts',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'fullTests',
    samplePath: readingV2StoragePaths.fullTests('full-test-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Teacher Lobby, Material Profile, library, assignment pickers',
    allowedRoles: ['teacher-owner', 'admin'],
    readWriteMode: 'read-write',
    queryPattern: 'owner, state, library visibility',
    indexRequirement: 'owner/state/library visibility index',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'archive/retire preserves historical attempts',
    projectionSafetyRule: 'assembly metadata only; runtime receives projections',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'materialMetadata',
    samplePath: readingV2StoragePaths.materialMetadata('material-1'),
    owningService: 'readingV2PublishPipeline.service',
    consumingSurface: 'Teacher Lobby, Material Profile, library, assignment pickers, and launch resolvers',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'read-write',
    queryPattern: 'materialId plus owner/visibility fields for existing listing surfaces',
    indexRequirement: 'material metadata lookup by materialId and owner/visibility',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'current relationship-facing metadata may update on republish; snapshots remain immutable',
    projectionSafetyRule: 'metadata is package/listing truth only and never canonical task content',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'relationshipIndexes',
    samplePath: readingV2StoragePaths.relationshipIndexes('teacher-lobby', 'material-1'),
    owningService: 'readingV2PublishPipeline.service',
    consumingSurface: 'Existing platform relationship surfaces and launch resolvers',
    allowedRoles: ['student', 'teacher-owner', 'admin', 'system'],
    readWriteMode: 'read-write',
    queryPattern: 'surface plus materialId, with snapshot/source tags',
    indexRequirement: 'surface/material lookup for platform fan-out reads',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'relationship index points at latest published snapshot; historical attempts keep their own snapshot binding',
    projectionSafetyRule: 'index stores references to approved metadata/projections, not canonical drafts',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'publishedSnapshots',
    samplePath: readingV2StoragePaths.publishedSnapshots('material-1', 'snapshot-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'publish pipeline, scoring, result snapshot binding',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'append-only',
    queryPattern: 'materialId plus snapshotVersionId',
    indexRequirement: 'materialId/snapshot version lookup',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'immutable historical truth; never mutate in place',
    projectionSafetyRule: 'canonical snapshot may contain answers and is never student-readable',
    forbiddenFields: [],
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'previewPayloads',
    samplePath: readingV2StoragePaths.previewPayloads('draft-1'),
    owningService: 'readingV2Projection.service',
    consumingSurface: 'teacher-only Studio preview',
    allowedRoles: ['teacher-owner', 'admin'],
    readWriteMode: 'read-write',
    queryPattern: 'draftId',
    indexRequirement: 'draftId lookup',
    frequencyClass: 'high',
    retentionDeletionBehavior: 'ephemeral; regenerated from draft',
    projectionSafetyRule: 'preview writes no assignment, session, attempt, homework, course, or result records',
    forbiddenFields: ['liveAttemptState'],
    atomicityDecision: 'single-write',
  },
  {
    pathClass: 'studentSafeTests',
    samplePath: readingV2StoragePaths.studentSafeTests('material-1', 'snapshot-1'),
    owningService: 'readingV2Projection.service',
    consumingSurface: 'solo, homework, course, and public library launch shells',
    allowedRoles: ['student', 'teacher-owner', 'admin', 'system'],
    readWriteMode: 'read',
    queryPattern: 'testId',
    indexRequirement: 'testId lookup',
    frequencyClass: 'high',
    retentionDeletionBehavior: 'regenerated on publish; old versions stay bound to attempts',
    projectionSafetyRule: 'student-safe projection strips answer keys, diagnostics, import evidence, and hidden provenance',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'sessionSafePayloads',
    samplePath: readingV2StoragePaths.sessionSafePayloads('ABC123', 'snapshot-1'),
    owningService: 'readingV2Projection.service',
    consumingSurface: 'live session route',
    allowedRoles: ['student', 'teacher-owner', 'admin', 'system'],
    readWriteMode: 'read-write',
    queryPattern: 'sessionCode plus testId/version staleness check',
    indexRequirement: 'sessionCode lookup',
    frequencyClass: 'high',
    retentionDeletionBehavior: 'cleared when live session ends',
    projectionSafetyRule: 'derived from student-safe payload, never from a second canonical model',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'reviewProjections',
    samplePath: readingV2StoragePaths.reviewProjections('material-1', 'snapshot-1'),
    owningService: 'readingV2Projection.service',
    consumingSurface: 'existing result/review shell adapters',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'read',
    queryPattern: 'materialId plus snapshotVersionId',
    indexRequirement: 'material/snapshot lookup for result adapter binding',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'regenerated on publish and bound by snapshot version for historical review',
    projectionSafetyRule: 'review projection is not editable content truth and is never a student runtime payload',
    forbiddenFields: ['canonicalEditableDraft'],
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'attempts',
    samplePath: readingV2StoragePaths.attempts('attempt-1'),
    owningService: 'readingV2Result.service',
    consumingSurface: 'student runtime submit pipeline',
    allowedRoles: ['student', 'system'],
    readWriteMode: 'append-only',
    queryPattern: 'studentId plus material/session context',
    indexRequirement: 'student/context lookup',
    frequencyClass: 'high',
    retentionDeletionBehavior: 'append-only attempt history retained with result',
    projectionSafetyRule: 'stores answers by stable interaction IDs and snapshot/session version',
    forbiddenFields: ['scoringRule', 'authorDiagnostics', 'importEvidence', 'hiddenProvenance'],
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'results',
    samplePath: readingV2StoragePaths.results('result-1'),
    owningService: 'readingV2Result.service',
    consumingSurface: 'existing result, review, feedback, and academic record shells',
    allowedRoles: ['student', 'teacher-owner', 'admin', 'system'],
    readWriteMode: 'read-write',
    queryPattern: 'resultId plus existing fan-out indexes',
    indexRequirement: 'existing result relationship indexes',
    frequencyClass: 'high',
    retentionDeletionBehavior: 'historical truth retained; regrade appends artifacts',
    projectionSafetyRule: 'student views are sanitized by release policy',
    forbiddenFields: ['scoringRule', 'authorDiagnostics', 'importEvidence', 'hiddenProvenance'],
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'regradeArtifacts',
    samplePath: readingV2StoragePaths.regradeArtifacts('result-1', 'regrade-1'),
    owningService: 'readingV2Result.service',
    consumingSurface: 'existing result, review, feedback, and regrade shells',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'append-only',
    queryPattern: 'resultId plus regradeId',
    indexRequirement: 'result/regrade lookup',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'append-only regrade history; historical result truth is never replaced',
    projectionSafetyRule: 'stores reviewed score artifact only; student views still pass release policy',
    forbiddenFields: ['authorDiagnostics', 'importEvidence', 'hiddenProvenance'],
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'reviewIndexes',
    samplePath: readingV2StoragePaths.reviewIndexes('result-1'),
    owningService: 'readingV2Result.service',
    consumingSurface: 'existing ReviewTab and result adapters',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'read-write',
    queryPattern: 'resultId and taskGroupId',
    indexRequirement: 'result/taskGroup lookup',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'regenerated from saved result and snapshot',
    projectionSafetyRule: 'review projection is not editable content truth',
    forbiddenFields: ['canonicalEditableDraft'],
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'analyticsOutputs',
    samplePath: readingV2StoragePaths.analyticsOutputs('material-1', 'snapshot-1'),
    owningService: 'feature registry observability plumbing',
    consumingSurface: 'teacher/admin analytics and support workflows',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'append-only',
    queryPattern: 'materialId, family, officialTaskType',
    indexRequirement: 'material/family/type aggregation index',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'privacy-safe aggregate retention policy',
    projectionSafetyRule: 'no student-hidden answer keys or author-only diagnostics',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'single-write',
  },
  {
    pathClass: 'provenance',
    samplePath: readingV2StoragePaths.provenance('provenance-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Studio audit and Material Profile dependency display',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'append-only',
    queryPattern: 'source material, asset, task group',
    indexRequirement: 'source object lookup',
    frequencyClass: 'low',
    retentionDeletionBehavior: 'hidden audit history retained with material',
    projectionSafetyRule: 'hidden provenance never reaches student-safe or session-safe projections',
    forbiddenFields: ['studentVisibleProvenance'],
    atomicityDecision: 'batch-required',
  },
  {
    pathClass: 'whereUsedGraph',
    samplePath: readingV2StoragePaths.whereUsedGraph('asset-1'),
    owningService: 'readingV2Repository.service',
    consumingSurface: 'Studio dependency warnings and Material Profile where-used display',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'read-write',
    queryPattern: 'passageAssetId',
    indexRequirement: 'asset dependency lookup',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'preserve dependencies for archived and published materials',
    projectionSafetyRule: 'dependency graph is teacher/admin only',
    forbiddenFields: ['studentVisibleDependencyGraph'],
    atomicityDecision: 'transaction-required',
  },
  {
    pathClass: 'publishCommits',
    samplePath: readingV2StoragePaths.publishCommits('material-1', 'snapshot-1'),
    owningService: 'readingV2FirebasePublishAdapter.service',
    consumingSurface: 'publish retry/idempotency boundary',
    allowedRoles: ['teacher-owner', 'admin', 'system'],
    readWriteMode: 'append-only',
    queryPattern: 'materialId plus snapshotVersionId commit marker',
    indexRequirement: 'commit marker lookup before retrying publish writes',
    frequencyClass: 'medium',
    retentionDeletionBehavior: 'retain as publish audit/idempotency evidence with the snapshot',
    projectionSafetyRule: 'commit marker stores operation keys and paths only, not editable canonical content',
    forbiddenFields: READING_V2_FORBIDDEN_STUDENT_FIELDS,
    atomicityDecision: 'batch-required',
  },
] as const satisfies readonly ReadingV2OperationalMatrixEntry[];

export const getReadingV2OperationalMatrixEntry = (
  pathClass: ReadingV2StoragePathClass,
): ReadingV2OperationalMatrixEntry => {
  const entry = READING_V2_OPERATIONAL_MATRIX.find((candidate) => candidate.pathClass === pathClass);

  if (!entry) {
    throw new Error(`Missing Reading V2 operational matrix entry for ${pathClass}.`);
  }

  return entry;
};
