import { containsBookImpactSensitiveKey, freezeBookImpactValue, isBookImpactDiscoverySafeId, isBookImpactDiscoveryTimestamp } from './bookImpactDiscovery.types';
import { BOOK_CONTEXT_IMPACT_DISCOVERY_VERSION, BOOK_CONTEXT_IMPACT_EFFECTS, BOOK_CONTEXT_IMPACT_MAX_CONTEXTS, BOOK_CONTEXT_IMPACT_MAX_PLACEMENTS, type BookContextImpactAuthorization, type BookContextImpactFailure, type BookContextImpactInput, type BookContextImpactKind, type BookContextImpactQuery, type BookContextImpactReader, type BookContextImpactResult } from './bookContextImpactDiscovery.types';

export interface BookContextImpactPolicy { readonly adapterId: string; readonly adapterVersion: number; readonly contextKind: BookContextImpactKind; readonly ownerScope: BookContextImpactAuthorization['ownerScope']; readonly owns: (value: BookContextImpactInput, actorId: string) => boolean; }
const own = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value) && Object.keys(value as object).length === keys.length && keys.every((key) => Object.prototype.hasOwnProperty.call(value, key));
const positive = (value: unknown): value is number => Number.isSafeInteger(value) && (value as number) > 0;
const id = (value: unknown): value is string => isBookImpactDiscoverySafeId(value);
const identity = (value: unknown): boolean => {
  if (!value || typeof value !== 'object') return false;
  const item = value as Record<string, unknown>;
  if (item.kind === 'course') return own(item, ['kind', 'courseId', 'moduleId', 'courseMaterialId', 'unitStableKey', 'unitVersionId', 'sourceVersionId', 'placementRevision']) && ['courseId', 'moduleId', 'courseMaterialId', 'unitStableKey', 'unitVersionId', 'sourceVersionId'].every((key) => id(item[key])) && positive(item.placementRevision);
  if (item.kind === 'class') return own(item, ['kind', 'classId', 'copyId', 'classPlacementId', 'courseMaterialId', 'unitStableKey', 'unitVersionId', 'sourceVersionId', 'placementRevision']) && ['classId', 'copyId', 'classPlacementId', 'courseMaterialId', 'unitStableKey', 'unitVersionId', 'sourceVersionId'].every((key) => id(item[key])) && positive(item.placementRevision);
  return item.kind === 'public-reference' && own(item, ['kind', 'referenceKind', 'referenceId', 'sourceBookId', 'targetBookId', 'targetPlacementId', 'sourceOwnerId', 'downstreamOwnerId', 'provenanceId']) && (item.referenceKind === 'reference' || item.referenceKind === 'fork') && ['referenceId', 'sourceBookId', 'targetBookId', 'targetPlacementId', 'sourceOwnerId', 'downstreamOwnerId', 'provenanceId'].every((key) => id(item[key]));
};
const valid = (value: unknown, policy: BookContextImpactPolicy, actorId: string, now: string): value is BookContextImpactInput => {
  const keys = ['contextId', 'kind', 'ownerId', 'recipientId', 'bindingId', 'bindingRevision', 'bookId', 'publicationId', 'manifestVersionId', 'status', 'lifecycle', 'identity', 'placements', 'classification', 'sourceReplacement', 'observedAt'];
  if (!own(value, keys) || containsBookImpactSensitiveKey(value)) return false;
  const item = value as Record<string, unknown>;
  if (item.kind !== policy.contextKind || !['active', 'closed', 'archived', 'revoked'].includes(String(item.status)) || !['not-started', 'in-progress', 'submitted', 'completed'].includes(String(item.lifecycle)) || ![item.contextId, item.ownerId, item.recipientId, item.bindingId, item.bookId, item.publicationId, item.manifestVersionId].every(id) || !positive(item.bindingRevision) || !identity(item.identity) || !isBookImpactDiscoveryTimestamp(item.observedAt) || Date.parse(item.observedAt as string) > Date.parse(now) || !Array.isArray(item.placements) || item.placements.length === 0 || item.placements.length > BOOK_CONTEXT_IMPACT_MAX_PLACEMENTS) return false;
  const placementIds = new Set<string>();
  for (const placement of item.placements) { if (!own(placement, ['placementId', 'activityId', 'activityVersionId', 'sourceVersionId', 'order']) || ![placement.placementId, placement.activityId, placement.activityVersionId, placement.sourceVersionId].every(id) || !Number.isSafeInteger(placement.order) || (placement.order as number) < 0 || placementIds.has(placement.placementId as string)) return false; placementIds.add(placement.placementId as string); }
  const classification = item.classification as Record<string, unknown>;
  const replacement = item.sourceReplacement as Record<string, unknown>;
  if (!own(classification, ['primaryEffect', 'effects', 'reasons', 'requiresRedo', 'requiresRegrade']) || !BOOK_CONTEXT_IMPACT_EFFECTS.includes(classification.primaryEffect as never) || !Array.isArray(classification.effects) || classification.effects.length === 0 || !classification.effects.every((effect) => BOOK_CONTEXT_IMPACT_EFFECTS.includes(effect)) || !Array.isArray(classification.reasons) || !classification.reasons.every((reason) => typeof reason === 'string' && reason.length <= 256) || typeof classification.requiresRedo !== 'boolean' || typeof classification.requiresRegrade !== 'boolean' || !own(replacement, ['mode', 'ownerChoice', 'replacementSourceVersionId']) || !['invalidation-only', 'owner-adopts-replacement'].includes(String(replacement.mode)) || !['retain-owner', 'owner-adopts-replacement', 'invalidate-context'].includes(String(replacement.ownerChoice)) || (replacement.replacementSourceVersionId !== null && !id(replacement.replacementSourceVersionId)) || (replacement.mode === 'invalidation-only' && (replacement.ownerChoice === 'owner-adopts-replacement' || replacement.replacementSourceVersionId !== null))) return false;
  return policy.owns(item as unknown as BookContextImpactInput, actorId);
};
const blocked = (query: BookContextImpactQuery, policy: BookContextImpactPolicy, code: BookContextImpactFailure): BookContextImpactResult => ({ status: 'blocked', version: BOOK_CONTEXT_IMPACT_DISCOVERY_VERSION, adapterId: policy.adapterId, adapterVersion: policy.adapterVersion, contextKind: policy.contextKind, evaluatedAt: query?.evaluatedAt ?? '', code });
export const createBookContextImpactAdapter = (reader: BookContextImpactReader, policy: BookContextImpactPolicy) => Object.freeze({ discover: async (query: BookContextImpactQuery): Promise<BookContextImpactResult> => {
  if (!query || !id(query.actorId)) return blocked(query, policy, 'invalid-actor');
  if (!isBookImpactDiscoveryTimestamp(query.evaluatedAt)) return blocked(query, policy, 'malformed');
  const limit = query.limit ?? BOOK_CONTEXT_IMPACT_MAX_CONTEXTS;
  if (!positive(limit) || limit > BOOK_CONTEXT_IMPACT_MAX_CONTEXTS) return blocked(query, policy, 'unbounded');
  let auth; try { auth = await reader.authorize({ actorId: query.actorId }); } catch { return blocked(query, policy, 'uncertain'); }
  if (!auth.authorized) return blocked(query, policy, auth.code);
  if (auth.actorId !== query.actorId || auth.contextKind !== policy.contextKind || auth.ownerScope !== policy.ownerScope || !positive(auth.maxContexts) || auth.maxContexts > BOOK_CONTEXT_IMPACT_MAX_CONTEXTS) return blocked(query, policy, 'unauthorized');
  let page; try { page = await reader.readAuthorizedContexts({ actorId: query.actorId, limit: Math.min(limit, auth.maxContexts) }); } catch { return blocked(query, policy, 'missing'); }
  if (!page || page.complete !== true || !Array.isArray(page.contexts) || page.contexts.length > Math.min(limit, auth.maxContexts)) return blocked(query, policy, 'unbounded');
  const ids = new Set<string>(); const bindings = new Set<string>(); const impacts: BookContextImpactInput[] = [];
  for (const record of page.contexts) { if (!valid(record, policy, query.actorId, query.evaluatedAt)) return blocked(query, policy, 'malformed'); const context = record; if (ids.has(context.contextId) || bindings.has(context.bindingId)) return blocked(query, policy, 'ambiguous'); ids.add(context.contextId); bindings.add(context.bindingId); if (context.status === 'active') impacts.push(structuredClone(context)); }
  return freezeBookImpactValue({ status: 'ok' as const, version: BOOK_CONTEXT_IMPACT_DISCOVERY_VERSION, adapterId: policy.adapterId, adapterVersion: policy.adapterVersion, contextKind: policy.contextKind, evaluatedAt: query.evaluatedAt, impacts: impacts.sort((left, right) => left.contextId.localeCompare(right.contextId)) });
} });
